name: CI/CD WorkFlow (main)

on:
  pull_request_target:
    branches: ["main"]
    types:
      - closed
  workflow_dispatch:

jobs:
  tests:
    name: "Run Tests"
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run tests
        env:
          MEDDLY_DB_STRING: ${{ secrets.MEDDLY_DB_STRING }}
          MEDDLY_FIREBASE_JSON: ${{ secrets.MEDDLY_FIREBASE_JSON }}
          MEDDLY_FIREBASE_KEY: ${{ secrets.MEDDLY_FIREBASE_KEY }}
          MEDDLY_FIREBASE_PRIVATE_KEY: ${{ secrets.MEDDLY_FIREBASE_PRIVATE_KEY }}
        run: |
          pytest

  push_image:
    name: "Push Docker image to Docker Hub"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ignaciopieve/meddly-back:latest

  deploy:
    name: "Deploy to EC2"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Pull changes
        run: |
          ssh staging 'cd /home/ubuntu/Meddly && git pull'
      - name: Stop Container
        run: ssh staging 'docker stop meddly-container' || true

      - name: Delete container and image
        run: |
          ssh staging 'docker rm meddly-container' || true
          ssh staging 'docker rmi meddly' || true

      - name: Build image
        run: ssh staging 'cd /home/ubuntu/Meddly && docker build -t meddly .'

      - name: Run container
        run: >
          ssh staging "docker run -d --name meddly-container -p 8000:8000
          --env MEDDLY_DB_STRING='${{ secrets.MEDDLY_DB_STRING }}'
          --env MEDDLY_FIREBASE_JSON='${{ secrets.MEDDLY_FIREBASE_JSON }}'
          --env MEDDLY_FIREBASE_KEY='${{ secrets.MEDDLY_FIREBASE_KEY }}'
          --env MEDDLY_FIREBASE_PRIVATE_KEY='${{ secrets.MEDDLY_FIREBASE_PRIVATE_KEY }}' meddly"